package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Erba06tbId generated by hbm2java
 */
@Embeddable
public class AlmAssetDurationId implements java.io.Serializable {

	private String basDt;
	private String acntLcls;
	private String acntMcls;
	private String acntScls;
	private String portseg;
	private String assetId;

	public AlmAssetDurationId() {
	}

	public AlmAssetDurationId(String basDt, String acntLcls, String acntMcls, String acntScls, String portseg, String assetId) {
		this.basDt = basDt;
		this.acntLcls = acntLcls;
		this.acntMcls = acntMcls;
		this.acntScls = acntScls;
		this.portseg = portseg;
		this.assetId = assetId;
	}

	@Column(name = "BAS_DT", nullable = false, length = 8)
	public String getBasDt() {
		return this.basDt;
	}

	public void setBasDt(String basDt) {
		this.basDt = basDt;
	}

	@Column(name = "ACNT_LCLS", nullable = false, length = 20)
	public String getAcntLcls() {
		return this.acntLcls;
	}

	public void setAcntLcls(String acntLcls) {
		this.acntLcls = acntLcls;
	}

	@Column(name = "ACNT_MCLS", nullable = false, length = 20)
	public String getAcntMcls() {
		return this.acntMcls;
	}

	public void setAcntMcls(String acntMcls) {
		this.acntMcls = acntMcls;
	}

	@Column(name = "ACNT_SCLS", nullable = false, length = 20)
	public String getAcntScls() {
		return this.acntScls;
	}

	public void setAcntScls(String acntScls) {
		this.acntScls = acntScls;
	}

	@Column(name = "PORTSEG", nullable = false, length = 20)
	public String getPortseg() {
		return this.portseg;
	}

	public void setPortseg(String portseg) {
		this.portseg = portseg;
	}

	@Column(name = "ASSET_ID", nullable = false, length = 50)
	public String getAssetId() {
		return this.assetId;
	}

	public void setAssetId(String assetId) {
		this.assetId = assetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AlmAssetDurationId))
			return false;
		AlmAssetDurationId castOther = (AlmAssetDurationId) other;

		return ((this.getBasDt() == castOther.getBasDt()) || (this.getBasDt() != null && castOther.getBasDt() != null && this
				.getBasDt().equals(castOther.getBasDt())))
				&& ((this.getAcntLcls() == castOther.getAcntLcls()) || (this.getAcntLcls() != null
						&& castOther.getAcntLcls() != null && this.getAcntLcls().equals(castOther.getAcntLcls())))
				&& ((this.getAcntMcls() == castOther.getAcntMcls()) || (this.getAcntMcls() != null
						&& castOther.getAcntMcls() != null && this.getAcntMcls().equals(castOther.getAcntMcls())))
				&& ((this.getAcntScls() == castOther.getAcntScls()) || (this.getAcntScls() != null
						&& castOther.getAcntScls() != null && this.getAcntScls().equals(castOther.getAcntScls())))
				&& ((this.getPortseg() == castOther.getPortseg()) || (this.getPortseg() != null
						&& castOther.getPortseg() != null && this.getPortseg().equals(castOther.getPortseg())))
				&& ((this.getAssetId() == castOther.getAssetId()) || (this.getAssetId() != null
						&& castOther.getAssetId() != null && this.getAssetId().equals(castOther.getAssetId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBasDt() == null ? 0 : this.getBasDt().hashCode());
		result = 37 * result + (getAcntLcls() == null ? 0 : this.getAcntLcls().hashCode());
		result = 37 * result + (getAcntMcls() == null ? 0 : this.getAcntMcls().hashCode());
		result = 37 * result + (getAcntScls() == null ? 0 : this.getAcntScls().hashCode());
		result = 37 * result + (getPortseg() == null ? 0 : this.getPortseg().hashCode());
		result = 37 * result + (getAssetId() == null ? 0 : this.getAssetId().hashCode());
		return result;
	}

}
