package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba09tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA09TB")
public class BenchmarkExpectedReturn implements java.io.Serializable {

	private BenchmarkExpectedReturnId id;
	private String applyEndDt;
	private BigDecimal expYield;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public BenchmarkExpectedReturn() {
	}

	public BenchmarkExpectedReturn(BenchmarkExpectedReturnId id) {
		this.id = id;
	}

	public BenchmarkExpectedReturn(BenchmarkExpectedReturnId id, String applyEndDt, BigDecimal expYield, String procClerkNo, Serializable dbChngDttm) {
		this.id = id;
		this.applyEndDt = applyEndDt;
		this.expYield = expYield;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bmkId", column = @Column(name = "BMK_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "applyStartDt", column = @Column(name = "APPLY_START_DT", nullable = false, length = 8)) })
	public BenchmarkExpectedReturnId getId() {
		return this.id;
	}

	public void setId(BenchmarkExpectedReturnId id) {
		this.id = id;
	}

	@Column(name = "APPLY_END_DT", length = 8)
	public String getApplyEndDt() {
		return this.applyEndDt;
	}

	public void setApplyEndDt(String applyEndDt) {
		this.applyEndDt = applyEndDt;
	}

	@Column(name = "EXP_YIELD", precision = 10, scale = 4)
	public BigDecimal getExpYield() {
		return this.expYield;
	}

	public void setExpYield(BigDecimal expYield) {
		this.expYield = expYield;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
