package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba08tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA08TB")
public class BenchmarkWeight implements java.io.Serializable {

	private BenchmarkWeightId id;
	private String cpsnIdxNm;
	private BigDecimal cpsnWght;
	private BigDecimal cpsnSpread;
	private String srcTableNm;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public BenchmarkWeight() {
	}

	public BenchmarkWeight(BenchmarkWeightId id) {
		this.id = id;
	}

	public BenchmarkWeight(BenchmarkWeightId id, String cpsnIdxNm, BigDecimal cpsnWght, BigDecimal cpsnSpread, String srcTableNm,
			String procClerkNo, Serializable dbChngDttm) {
		this.id = id;
		this.cpsnIdxNm = cpsnIdxNm;
		this.cpsnWght = cpsnWght;
		this.cpsnSpread = cpsnSpread;
		this.srcTableNm = srcTableNm;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bmkId", column = @Column(name = "BMK_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "cpsnIdxId", column = @Column(name = "CPSN_IDX_ID", nullable = false, length = 120)) })
	public BenchmarkWeightId getId() {
		return this.id;
	}

	public void setId(BenchmarkWeightId id) {
		this.id = id;
	}

	@Column(name = "CPSN_IDX_NM", length = 100)
	public String getCpsnIdxNm() {
		return this.cpsnIdxNm;
	}

	public void setCpsnIdxNm(String cpsnIdxNm) {
		this.cpsnIdxNm = cpsnIdxNm;
	}

	@Column(name = "CPSN_WGHT", precision = 10, scale = 4)
	public BigDecimal getCpsnWght() {
		return this.cpsnWght;
	}

	public void setCpsnWght(BigDecimal cpsnWght) {
		this.cpsnWght = cpsnWght;
	}

	@Column(name = "CPSN_SPREAD", precision = 10, scale = 4)
	public BigDecimal getCpsnSpread() {
		return this.cpsnSpread;
	}

	public void setCpsnSpread(BigDecimal cpsnSpread) {
		this.cpsnSpread = cpsnSpread;
	}

	@Column(name = "SRC_TABLE_NM", length = 100)
	public String getSrcTableNm() {
		return this.srcTableNm;
	}

	public void setSrcTableNm(String srcTableNm) {
		this.srcTableNm = srcTableNm;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
