package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba13tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA13TB")
public class BenchmarkReturn implements java.io.Serializable {

	private BenchmarkReturnId id;
	private BigDecimal bmkIdx;
	private BigDecimal bmkIdxYield;
	private BigDecimal bmkMmYield;
	private BigDecimal bmkAcmYield;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public BenchmarkReturn() {
	}

	public BenchmarkReturn(BenchmarkReturnId id) {
		this.id = id;
	}

	public BenchmarkReturn(BenchmarkReturnId id, BigDecimal bmkIdx, BigDecimal bmkIdxYield, BigDecimal bmkMmYield,
			BigDecimal bmkAcmYield, String procClerkNo, Serializable dbChngDttm) {
		this.id = id;
		this.bmkIdx = bmkIdx;
		this.bmkIdxYield = bmkIdxYield;
		this.bmkMmYield = bmkMmYield;
		this.bmkAcmYield = bmkAcmYield;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "basDt", column = @Column(name = "BAS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "bmkId", column = @Column(name = "BMK_ID", nullable = false, length = 20)) })
	public BenchmarkReturnId getId() {
		return this.id;
	}

	public void setId(BenchmarkReturnId id) {
		this.id = id;
	}

	@Column(name = "BMK_IDX", precision = 18, scale = 4)
	public BigDecimal getBmkIdx() {
		return this.bmkIdx;
	}

	public void setBmkIdx(BigDecimal bmkIdx) {
		this.bmkIdx = bmkIdx;
	}

	@Column(name = "BMK_IDX_YIELD", precision = 10, scale = 4)
	public BigDecimal getBmkIdxYield() {
		return this.bmkIdxYield;
	}

	public void setBmkIdxYield(BigDecimal bmkIdxYield) {
		this.bmkIdxYield = bmkIdxYield;
	}

	@Column(name = "BMK_MM_YIELD", precision = 10, scale = 4)
	public BigDecimal getBmkMmYield() {
		return this.bmkMmYield;
	}

	public void setBmkMmYield(BigDecimal bmkMmYield) {
		this.bmkMmYield = bmkMmYield;
	}

	@Column(name = "BMK_ACM_YIELD", precision = 10, scale = 4)
	public BigDecimal getBmkAcmYield() {
		return this.bmkAcmYield;
	}

	public void setBmkAcmYield(BigDecimal bmkAcmYield) {
		this.bmkAcmYield = bmkAcmYield;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
