package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Erba02tbId generated by hbm2java
 */
@Embeddable
public class BucketMappingId implements java.io.Serializable {

	private String bucketId;
	private String segId;

	public BucketMappingId() {
	}

	public BucketMappingId(String bucketId, String segId) {
		this.bucketId = bucketId;
		this.segId = segId;
	}

	@Column(name = "BUCKET_ID", nullable = false, length = 20)
	public String getBucketId() {
		return this.bucketId;
	}

	public void setBucketId(String bucketId) {
		this.bucketId = bucketId;
	}

	@Column(name = "SEG_ID", nullable = false, length = 20)
	public String getSegId() {
		return this.segId;
	}

	public void setSegId(String segId) {
		this.segId = segId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BucketMappingId))
			return false;
		BucketMappingId castOther = (BucketMappingId) other;

		return ((this.getBucketId() == castOther.getBucketId()) || (this.getBucketId() != null
				&& castOther.getBucketId() != null && this.getBucketId().equals(castOther.getBucketId())))
				&& ((this.getSegId() == castOther.getSegId()) || (this.getSegId() != null
						&& castOther.getSegId() != null && this.getSegId().equals(castOther.getSegId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBucketId() == null ? 0 : this.getBucketId().hashCode());
		result = 37 * result + (getSegId() == null ? 0 : this.getSegId().hashCode());
		return result;
	}

}
