package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba02tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA02TB", catalog="ERMAMS")
public class BucketMapping implements java.io.Serializable {

	private BucketMappingId id;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public BucketMapping() {
	}

	public BucketMapping(BucketMappingId id) {
		this.id = id;
	}

	public BucketMapping(BucketMappingId id, String procClerkNo, Serializable dbChngDttm) {
		this.id = id;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "bucketId", column = @Column(name = "BUCKET_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "segId", column = @Column(name = "SEG_ID", nullable = false, length = 20)) })
	public BucketMappingId getId() {
		return this.id;
	}

	public void setId(BucketMappingId id) {
		this.id = id;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}

//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
