package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba05tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA05TB")
public class DebtDuration implements java.io.Serializable {

	private DebtDurationId id;
	private Long bookAmt;
	private Long evalAmt;
	private BigDecimal durt;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public DebtDuration() {
	}

	public DebtDuration(DebtDurationId id) {
		this.id = id;
	}

	public DebtDuration(DebtDurationId id, Long bookAmt, Long evalAmt, BigDecimal durt, String procClerkNo,
			Serializable dbChngDttm) {
		this.id = id;
		this.bookAmt = bookAmt;
		this.evalAmt = evalAmt;
		this.durt = durt;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "basDt", column = @Column(name = "BAS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "portseg", column = @Column(name = "PORTSEG", nullable = false, length = 20)) })
	public DebtDurationId getId() {
		return this.id;
	}

	public void setId(DebtDurationId id) {
		this.id = id;
	}

	@Column(name = "BOOK_AMT", precision = 18, scale = 0)
	public Long getBookAmt() {
		return this.bookAmt;
	}

	public void setBookAmt(Long bookAmt) {
		this.bookAmt = bookAmt;
	}

	@Column(name = "EVAL_AMT", precision = 18, scale = 0)
	public Long getEvalAmt() {
		return this.evalAmt;
	}

	public void setEvalAmt(Long evalAmt) {
		this.evalAmt = evalAmt;
	}

	@Column(name = "DURT", precision = 10, scale = 4)
	public BigDecimal getDurt() {
		return this.durt;
	}

	public void setDurt(BigDecimal durt) {
		this.durt = durt;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
