package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Erba04tbId generated by hbm2java
 */
@Embeddable
public class DebtCfId implements java.io.Serializable {

	private String basDt;
	private String portseg;
	private long exprMonths;

	public DebtCfId() {
	}

	public DebtCfId(String basDt, String portseg, long exprMonths) {
		this.basDt = basDt;
		this.portseg = portseg;
		this.exprMonths = exprMonths;
	}

	@Column(name = "BAS_DT", nullable = false, length = 8)
	public String getBasDt() {
		return this.basDt;
	}

	public void setBasDt(String basDt) {
		this.basDt = basDt;
	}

	@Column(name = "PORTSEG", nullable = false, length = 20)
	public String getPortseg() {
		return this.portseg;
	}

	public void setPortseg(String portseg) {
		this.portseg = portseg;
	}

	@Column(name = "EXPR_MONTHS", nullable = false, precision = 10, scale = 0)
	public long getExprMonths() {
		return this.exprMonths;
	}

	public void setExprMonths(long exprMonths) {
		this.exprMonths = exprMonths;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DebtCfId))
			return false;
		DebtCfId castOther = (DebtCfId) other;

		return ((this.getBasDt() == castOther.getBasDt()) || (this.getBasDt() != null && castOther.getBasDt() != null && this
				.getBasDt().equals(castOther.getBasDt())))
				&& ((this.getPortseg() == castOther.getPortseg()) || (this.getPortseg() != null
						&& castOther.getPortseg() != null && this.getPortseg().equals(castOther.getPortseg())))
				&& (this.getExprMonths() == castOther.getExprMonths());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBasDt() == null ? 0 : this.getBasDt().hashCode());
		result = 37 * result + (getPortseg() == null ? 0 : this.getPortseg().hashCode());
		result = 37 * result + (int) this.getExprMonths();
		return result;
	}

}
