package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba04tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA04TB")
public class DebtCf implements java.io.Serializable {

	private DebtCfId id;
	private Long cashflowAmt;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public DebtCf() {
	}

	public DebtCf(DebtCfId id) {
		this.id = id;
	}

	public DebtCf(DebtCfId id, Long cashflowAmt, String procClerkNo, Serializable dbChngDttm) {
		this.id = id;
		this.cashflowAmt = cashflowAmt;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "basDt", column = @Column(name = "BAS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "portseg", column = @Column(name = "PORTSEG", nullable = false, length = 20)),
			@AttributeOverride(name = "exprMonths", column = @Column(name = "EXPR_MONTHS", nullable = false, precision = 10, scale = 0)) })
	public DebtCfId getId() {
		return this.id;
	}

	public void setId(DebtCfId id) {
		this.id = id;
	}

	@Column(name = "CASHFLOW_AMT", precision = 18, scale = 0)
	public Long getCashflowAmt() {
		return this.cashflowAmt;
	}

	public void setCashflowAmt(Long cashflowAmt) {
		this.cashflowAmt = cashflowAmt;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
