package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Erba25tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA25TB")
public class OptimumProblem implements java.io.Serializable {

	private String optMthdlId;
	private String optMthdlNm;
	private String optMdlCd;
	private String segGrpId;
	private String riskTypeCd;
	private String reptExctYn;
	private BigDecimal sctnStartVal;
	private BigDecimal sctnEndVal;
	private BigDecimal sctnInterval;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public OptimumProblem() {
	}

	public OptimumProblem(String optMthdlId, String segGrpId) {
		this.optMthdlId = optMthdlId;
		this.segGrpId = segGrpId;
	}

	public OptimumProblem(String optMthdlId, String optMthdlNm, String optMdlCd, String segGrpId, String riskTypeCd,
			String reptExctYn, BigDecimal sctnStartVal, BigDecimal sctnEndVal, BigDecimal sctnInterval,
			String procClerkNo, Serializable dbChngDttm) {
		this.optMthdlId = optMthdlId;
		this.optMthdlNm = optMthdlNm;
		this.optMdlCd = optMdlCd;
		this.segGrpId = segGrpId;
		this.riskTypeCd = riskTypeCd;
		this.reptExctYn = reptExctYn;
		this.sctnStartVal = sctnStartVal;
		this.sctnEndVal = sctnEndVal;
		this.sctnInterval = sctnInterval;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@Id
	@Column(name = "OPT_MTHDL_ID", unique = true, nullable = false, length = 20)
	public String getOptMthdlId() {
		return this.optMthdlId;
	}

	public void setOptMthdlId(String optMthdlId) {
		this.optMthdlId = optMthdlId;
	}

	@Column(name = "OPT_MTHDL_NM", length = 100)
	public String getOptMthdlNm() {
		return this.optMthdlNm;
	}

	public void setOptMthdlNm(String optMthdlNm) {
		this.optMthdlNm = optMthdlNm;
	}

	@Column(name = "OPT_MDL_CD", length = 2)
	public String getOptMdlCd() {
		return this.optMdlCd;
	}

	public void setOptMdlCd(String optMdlCd) {
		this.optMdlCd = optMdlCd;
	}

	@Column(name = "SEG_GRP_ID", nullable = false, length = 20)
	public String getSegGrpId() {
		return this.segGrpId;
	}

	public void setSegGrpId(String segGrpId) {
		this.segGrpId = segGrpId;
	}

	@Column(name = "RISK_TYPE_CD", length = 2)
	public String getRiskTypeCd() {
		return this.riskTypeCd;
	}

	public void setRiskTypeCd(String riskTypeCd) {
		this.riskTypeCd = riskTypeCd;
	}

	@Column(name = "REPT_EXCT_YN", length = 1)
	public String getReptExctYn() {
		return this.reptExctYn;
	}

	public void setReptExctYn(String reptExctYn) {
		this.reptExctYn = reptExctYn;
	}

	@Column(name = "SCTN_START_VAL", precision = 20, scale = 6)
	public BigDecimal getSctnStartVal() {
		return this.sctnStartVal;
	}

	public void setSctnStartVal(BigDecimal sctnStartVal) {
		this.sctnStartVal = sctnStartVal;
	}

	@Column(name = "SCTN_END_VAL", precision = 20, scale = 6)
	public BigDecimal getSctnEndVal() {
		return this.sctnEndVal;
	}

	public void setSctnEndVal(BigDecimal sctnEndVal) {
		this.sctnEndVal = sctnEndVal;
	}

	@Column(name = "SCTN_INTERVAL", precision = 20, scale = 6)
	public BigDecimal getSctnInterval() {
		return this.sctnInterval;
	}

	public void setSctnInterval(BigDecimal sctnInterval) {
		this.sctnInterval = sctnInterval;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
