package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Erba28tbId generated by hbm2java
 */
@Embeddable
public class SaaEfficientFrontierId implements java.io.Serializable {

	private String basDt;
	private String optMthdlId;
	private long seqNum;

	public SaaEfficientFrontierId() {
	}

	public SaaEfficientFrontierId(String basDt, String optMthdlId, long seqNum) {
		this.basDt = basDt;
		this.optMthdlId = optMthdlId;
		this.seqNum = seqNum;
	}

	@Column(name = "BAS_DT", nullable = false, length = 8)
	public String getBasDt() {
		return this.basDt;
	}

	public void setBasDt(String basDt) {
		this.basDt = basDt;
	}

	@Column(name = "OPT_MTHDL_ID", nullable = false, length = 20)
	public String getOptMthdlId() {
		return this.optMthdlId;
	}

	public void setOptMthdlId(String optMthdlId) {
		this.optMthdlId = optMthdlId;
	}

	@Column(name = "SEQ_NUM", nullable = false, precision = 18, scale = 0)
	public long getSeqNum() {
		return this.seqNum;
	}

	public void setSeqNum(long seqNum) {
		this.seqNum = seqNum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SaaEfficientFrontierId))
			return false;
		SaaEfficientFrontierId castOther = (SaaEfficientFrontierId) other;

		return ((this.getBasDt() == castOther.getBasDt()) || (this.getBasDt() != null && castOther.getBasDt() != null && this
				.getBasDt().equals(castOther.getBasDt())))
				&& ((this.getOptMthdlId() == castOther.getOptMthdlId()) || (this.getOptMthdlId() != null
						&& castOther.getOptMthdlId() != null && this.getOptMthdlId().equals(castOther.getOptMthdlId())))
				&& (this.getSeqNum() == castOther.getSeqNum());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBasDt() == null ? 0 : this.getBasDt().hashCode());
		result = 37 * result + (getOptMthdlId() == null ? 0 : this.getOptMthdlId().hashCode());
		result = 37 * result + (int) this.getSeqNum();
		return result;
	}

}
