package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba30tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA30TB")
public class SaaEvaluation implements java.io.Serializable {

	private SaaEvaluationId id;
	private BigDecimal totIncomeAmt;
	private BigDecimal bmkIncomeAmt;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public SaaEvaluation() {
	}

	public SaaEvaluation(SaaEvaluationId id) {
		this.id = id;
	}

	public SaaEvaluation(SaaEvaluationId id, BigDecimal totIncomeAmt, BigDecimal bmkIncomeAmt, String procClerkNo,
			Serializable dbChngDttm) {
		this.id = id;
		this.totIncomeAmt = totIncomeAmt;
		this.bmkIncomeAmt = bmkIncomeAmt;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "basDt", column = @Column(name = "BAS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "optMthdlId", column = @Column(name = "OPT_MTHDL_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "segId", column = @Column(name = "SEG_ID", nullable = false, length = 20)) })
	public SaaEvaluationId getId() {
		return this.id;
	}

	public void setId(SaaEvaluationId id) {
		this.id = id;
	}

	@Column(name = "TOT_INCOME_AMT", precision = 18, scale = 4)
	public BigDecimal getTotIncomeAmt() {
		return this.totIncomeAmt;
	}

	public void setTotIncomeAmt(BigDecimal totIncomeAmt) {
		this.totIncomeAmt = totIncomeAmt;
	}

	@Column(name = "BMK_INCOME_AMT", precision = 18, scale = 4)
	public BigDecimal getBmkIncomeAmt() {
		return this.bmkIncomeAmt;
	}

	public void setBmkIncomeAmt(BigDecimal bmkIncomeAmt) {
		this.bmkIncomeAmt = bmkIncomeAmt;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
