package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba28tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA28TB")
public class SaaEfficientFrontier implements java.io.Serializable {

	private SaaEfficientFrontierId id;
	private String riskTypeCd;
	private BigDecimal var;
	private BigDecimal condpVar;
	private BigDecimal expYield;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public SaaEfficientFrontier() {
	}

	public SaaEfficientFrontier(SaaEfficientFrontierId id) {
		this.id = id;
	}

	public SaaEfficientFrontier(SaaEfficientFrontierId id, String riskTypeCd, BigDecimal var, BigDecimal condpVar, BigDecimal expYield,
			String procClerkNo, Serializable dbChngDttm) {
		this.id = id;
		this.riskTypeCd = riskTypeCd;
		this.var = var;
		this.condpVar = condpVar;
		this.expYield = expYield;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "basDt", column = @Column(name = "BAS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "optMthdlId", column = @Column(name = "OPT_MTHDL_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "seqNum", column = @Column(name = "SEQ_NUM", nullable = false, precision = 18, scale = 0)) })
	public SaaEfficientFrontierId getId() {
		return this.id;
	}

	public void setId(SaaEfficientFrontierId id) {
		this.id = id;
	}

	@Column(name = "RISK_TYPE_CD", length = 2)
	public String getRiskTypeCd() {
		return this.riskTypeCd;
	}

	public void setRiskTypeCd(String riskTypeCd) {
		this.riskTypeCd = riskTypeCd;
	}

	@Column(name = "VAR", precision = 20, scale = 4)
	public BigDecimal getVar() {
		return this.var;
	}

	public void setVar(BigDecimal var) {
		this.var = var;
	}

	@Column(name = "CONDP_VAR", precision = 20, scale = 4)
	public BigDecimal getCondpVar() {
		return this.condpVar;
	}

	public void setCondpVar(BigDecimal condpVar) {
		this.condpVar = condpVar;
	}

	@Column(name = "EXP_YIELD", precision = 10, scale = 4)
	public BigDecimal getExpYield() {
		return this.expYield;
	}

	public void setExpYield(BigDecimal expYield) {
		this.expYield = expYield;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
