package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Erba12tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA12TB")
public class SegmentCf implements java.io.Serializable {

	private SegmentCfId id;
	private Long exprMonths;
	private Long intCashflowAmt;
	private Long orgmnCashflowAmt;
	private Long cashflowAmt;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public SegmentCf() {
	}

	public SegmentCf(SegmentCfId id) {
		this.id = id;
	}

	public SegmentCf(SegmentCfId id, Long exprMonths, Long intCashflowAmt, Long orgmnCashflowAmt, Long cashflowAmt,
			String procClerkNo, Serializable dbChngDttm) {
		this.id = id;
		this.exprMonths = exprMonths;
		this.intCashflowAmt = intCashflowAmt;
		this.orgmnCashflowAmt = orgmnCashflowAmt;
		this.cashflowAmt = cashflowAmt;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "basDt", column = @Column(name = "BAS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "segId", column = @Column(name = "SEG_ID", nullable = false, length = 20)),
			@AttributeOverride(name = "exprCls", column = @Column(name = "EXPR_CLS", nullable = false, length = 10)) })
	public SegmentCfId getId() {
		return this.id;
	}

	public void setId(SegmentCfId id) {
		this.id = id;
	}

	@Column(name = "EXPR_MONTHS", precision = 10, scale = 0)
	public Long getExprMonths() {
		return this.exprMonths;
	}

	public void setExprMonths(Long exprMonths) {
		this.exprMonths = exprMonths;
	}

	@Column(name = "INT_CASHFLOW_AMT", precision = 18, scale = 0)
	public Long getIntCashflowAmt() {
		return this.intCashflowAmt;
	}

	public void setIntCashflowAmt(Long intCashflowAmt) {
		this.intCashflowAmt = intCashflowAmt;
	}

	@Column(name = "ORGMN_CASHFLOW_AMT", precision = 18, scale = 0)
	public Long getOrgmnCashflowAmt() {
		return this.orgmnCashflowAmt;
	}

	public void setOrgmnCashflowAmt(Long orgmnCashflowAmt) {
		this.orgmnCashflowAmt = orgmnCashflowAmt;
	}

	@Column(name = "CASHFLOW_AMT", precision = 18, scale = 0)
	public Long getCashflowAmt() {
		return this.cashflowAmt;
	}

	public void setCashflowAmt(Long cashflowAmt) {
		this.cashflowAmt = cashflowAmt;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
