package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Erba11tbId generated by hbm2java
 */
@Embeddable
public class SegmentScenarioId implements java.io.Serializable {

	private String basDt;
	private String segId;
	private String riskTypeCd;
	private long snroNo;

	public SegmentScenarioId() {
	}

	public SegmentScenarioId(String basDt, String segId, String riskTypeCd, long snroNo) {
		this.basDt = basDt;
		this.segId = segId;
		this.riskTypeCd = riskTypeCd;
		this.snroNo = snroNo;
	}

	@Column(name = "BAS_DT", nullable = false, length = 8)
	public String getBasDt() {
		return this.basDt;
	}

	public void setBasDt(String basDt) {
		this.basDt = basDt;
	}

	@Column(name = "SEG_ID", nullable = false, length = 20)
	public String getSegId() {
		return this.segId;
	}

	public void setSegId(String segId) {
		this.segId = segId;
	}

	@Column(name = "RISK_TYPE_CD", nullable = false, length = 2)
	public String getRiskTypeCd() {
		return this.riskTypeCd;
	}

	public void setRiskTypeCd(String riskTypeCd) {
		this.riskTypeCd = riskTypeCd;
	}

	@Column(name = "SNRO_NO", nullable = false, precision = 10, scale = 0)
	public long getSnroNo() {
		return this.snroNo;
	}

	public void setSnroNo(long snroNo) {
		this.snroNo = snroNo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SegmentScenarioId))
			return false;
		SegmentScenarioId castOther = (SegmentScenarioId) other;

		return ((this.getBasDt() == castOther.getBasDt()) || (this.getBasDt() != null && castOther.getBasDt() != null && this
				.getBasDt().equals(castOther.getBasDt())))
				&& ((this.getSegId() == castOther.getSegId()) || (this.getSegId() != null
						&& castOther.getSegId() != null && this.getSegId().equals(castOther.getSegId())))
				&& ((this.getRiskTypeCd() == castOther.getRiskTypeCd()) || (this.getRiskTypeCd() != null
						&& castOther.getRiskTypeCd() != null && this.getRiskTypeCd().equals(castOther.getRiskTypeCd())))
				&& (this.getSnroNo() == castOther.getSnroNo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBasDt() == null ? 0 : this.getBasDt().hashCode());
		result = 37 * result + (getSegId() == null ? 0 : this.getSegId().hashCode());
		result = 37 * result + (getRiskTypeCd() == null ? 0 : this.getRiskTypeCd().hashCode());
		result = 37 * result + (int) this.getSnroNo();
		return result;
	}

}
