package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Erba10tb generated by hbm2java
 */
@Entity
@Table(name = "ERBA10TB")
public class SegmentRiskMeasure implements java.io.Serializable {

	private SegmentRiskMeasureId id;
	private SaaSegment segment;
	private String exprCls;
	private String crdtOrdCd;
	private Long bookValAmt;
	private Long evalAmt;
	private Long nominalAmt;
	private Long FAdjstValAmt;
	private Long adjstValAmt;
	private Long FValValAmt;
	private Long valValAmt;
	private BigDecimal remnExprMonths;
	private BigDecimal durt;
	private BigDecimal ytm;
	private BigDecimal evalYield;
	private BigDecimal couponRate;
	private BigDecimal expYield;
//	private String procClerkNo;
//	private Serializable dbChngDttm;

	public SegmentRiskMeasure() {
	}

	public SegmentRiskMeasure(SegmentRiskMeasureId id) {
		this.id = id;
	}

	public SegmentRiskMeasure(SegmentRiskMeasureId id, String exprCls, String crdtOrdCd, Long bookValAmt, Long evalAmt, Long nominalAmt,
			Long FAdjstValAmt, Long adjstValAmt, Long FValValAmt, Long valValAmt, BigDecimal remnExprMonths,
			BigDecimal durt, BigDecimal ytm, BigDecimal evalYield, BigDecimal couponRate, BigDecimal expYield,
			String procClerkNo, Serializable dbChngDttm) {
		this.id = id;
		this.exprCls = exprCls;
		this.crdtOrdCd = crdtOrdCd;
		this.bookValAmt = bookValAmt;
		this.evalAmt = evalAmt;
		this.nominalAmt = nominalAmt;
		this.FAdjstValAmt = FAdjstValAmt;
		this.adjstValAmt = adjstValAmt;
		this.FValValAmt = FValValAmt;
		this.valValAmt = valValAmt;
		this.remnExprMonths = remnExprMonths;
		this.durt = durt;
		this.ytm = ytm;
		this.evalYield = evalYield;
		this.couponRate = couponRate;
		this.expYield = expYield;
//		this.procClerkNo = procClerkNo;
//		this.dbChngDttm = dbChngDttm;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "basDt", column = @Column(name = "BAS_DT", nullable = false, length = 8)),
			@AttributeOverride(name = "segId", column = @Column(name = "SEG_ID", nullable = false, length = 20)) })
	public SegmentRiskMeasureId getId() {
		return this.id;
	}

	public void setId(SegmentRiskMeasureId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEG_ID", nullable = false, insertable = false, updatable = false)
	@NotNull
	public SaaSegment getSegment() {
		return segment;
	}

	public void setSegment(SaaSegment segment) {
		this.segment = segment;
	}

	@Column(name = "EXPR_CLS", length = 10)
	public String getExprCls() {
		return this.exprCls;
	}

	public void setExprCls(String exprCls) {
		this.exprCls = exprCls;
	}

	@Column(name = "CRDT_ORD_CD", length = 10)
	public String getCrdtOrdCd() {
		return this.crdtOrdCd;
	}

	public void setCrdtOrdCd(String crdtOrdCd) {
		this.crdtOrdCd = crdtOrdCd;
	}

	@Column(name = "BOOK_VAL_AMT", precision = 18, scale = 0)
	public Long getBookValAmt() {
		return this.bookValAmt;
	}

	public void setBookValAmt(Long bookValAmt) {
		this.bookValAmt = bookValAmt;
	}

	@Column(name = "EVAL_AMT", precision = 18, scale = 0)
	public Long getEvalAmt() {
		return this.evalAmt;
	}

	public void setEvalAmt(Long evalAmt) {
		this.evalAmt = evalAmt;
	}

	@Column(name = "NOMINAL_AMT", precision = 18, scale = 0)
	public Long getNominalAmt() {
		return this.nominalAmt;
	}

	public void setNominalAmt(Long nominalAmt) {
		this.nominalAmt = nominalAmt;
	}

	@Column(name = "F_ADJST_VAL_AMT", precision = 18, scale = 0)
	public Long getFAdjstValAmt() {
		return this.FAdjstValAmt;
	}

	public void setFAdjstValAmt(Long FAdjstValAmt) {
		this.FAdjstValAmt = FAdjstValAmt;
	}

	@Column(name = "ADJST_VAL_AMT", precision = 18, scale = 0)
	public Long getAdjstValAmt() {
		return this.adjstValAmt;
	}

	public void setAdjstValAmt(Long adjstValAmt) {
		this.adjstValAmt = adjstValAmt;
	}

	@Column(name = "F_VAL_VAL_AMT", precision = 18, scale = 0)
	public Long getFValValAmt() {
		return this.FValValAmt;
	}

	public void setFValValAmt(Long FValValAmt) {
		this.FValValAmt = FValValAmt;
	}

	@Column(name = "VAL_VAL_AMT", precision = 18, scale = 0)
	public Long getValValAmt() {
		return this.valValAmt;
	}

	public void setValValAmt(Long valValAmt) {
		this.valValAmt = valValAmt;
	}

	@Column(name = "REMN_EXPR_MONTHS", precision = 10, scale = 4)
	public BigDecimal getRemnExprMonths() {
		return this.remnExprMonths;
	}

	public void setRemnExprMonths(BigDecimal remnExprMonths) {
		this.remnExprMonths = remnExprMonths;
	}

	@Column(name = "DURT", precision = 10, scale = 4)
	public BigDecimal getDurt() {
		return this.durt;
	}

	public void setDurt(BigDecimal durt) {
		this.durt = durt;
	}

	@Column(name = "YTM", precision = 10, scale = 4)
	public BigDecimal getYtm() {
		return this.ytm;
	}

	public void setYtm(BigDecimal ytm) {
		this.ytm = ytm;
	}

	@Column(name = "EVAL_YIELD", precision = 10, scale = 4)
	public BigDecimal getEvalYield() {
		return this.evalYield;
	}

	public void setEvalYield(BigDecimal evalYield) {
		this.evalYield = evalYield;
	}

	@Column(name = "COUPON_RATE", precision = 10, scale = 4)
	public BigDecimal getCouponRate() {
		return this.couponRate;
	}

	public void setCouponRate(BigDecimal couponRate) {
		this.couponRate = couponRate;
	}

	@Column(name = "EXP_YIELD", precision = 10, scale = 4)
	public BigDecimal getExpYield() {
		return this.expYield;
	}

	public void setExpYield(BigDecimal expYield) {
		this.expYield = expYield;
	}

//	@Column(name = "PROC_CLERK_NO", length = 10)
//	public String getProcClerkNo() {
//		return this.procClerkNo;
//	}
//
//	public void setProcClerkNo(String procClerkNo) {
//		this.procClerkNo = procClerkNo;
//	}
//
//	@Column(name = "DB_CHNG_DTTM")
//	public Serializable getDbChngDttm() {
//		return this.dbChngDttm;
//	}
//
//	public void setDbChngDttm(Serializable dbChngDttm) {
//		this.dbChngDttm = dbChngDttm;
//	}

}
