package com.eugenefe.saa.entity;

// Generated Sep 10, 2014 4:21:17 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Erba12tbId generated by hbm2java
 */
@Embeddable
public class SegmentCfId implements java.io.Serializable {

	private String basDt;
	private String segId;
	private String exprCls;

	public SegmentCfId() {
	}

	public SegmentCfId(String basDt, String segId, String exprCls) {
		this.basDt = basDt;
		this.segId = segId;
		this.exprCls = exprCls;
	}

	@Column(name = "BAS_DT", nullable = false, length = 8)
	public String getBasDt() {
		return this.basDt;
	}

	public void setBasDt(String basDt) {
		this.basDt = basDt;
	}

	@Column(name = "SEG_ID", nullable = false, length = 20)
	public String getSegId() {
		return this.segId;
	}

	public void setSegId(String segId) {
		this.segId = segId;
	}

	@Column(name = "EXPR_CLS", nullable = false, length = 10)
	public String getExprCls() {
		return this.exprCls;
	}

	public void setExprCls(String exprCls) {
		this.exprCls = exprCls;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SegmentCfId))
			return false;
		SegmentCfId castOther = (SegmentCfId) other;

		return ((this.getBasDt() == castOther.getBasDt()) || (this.getBasDt() != null && castOther.getBasDt() != null && this
				.getBasDt().equals(castOther.getBasDt())))
				&& ((this.getSegId() == castOther.getSegId()) || (this.getSegId() != null
						&& castOther.getSegId() != null && this.getSegId().equals(castOther.getSegId())))
				&& ((this.getExprCls() == castOther.getExprCls()) || (this.getExprCls() != null
						&& castOther.getExprCls() != null && this.getExprCls().equals(castOther.getExprCls())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getBasDt() == null ? 0 : this.getBasDt().hashCode());
		result = 37 * result + (getSegId() == null ? 0 : this.getSegId().hashCode());
		result = 37 * result + (getExprCls() == null ? 0 : this.getExprCls().hashCode());
		return result;
	}

}
